const express   = require('express')
const router    = express.Router()
global.query    = require("../model/query")
global.respons  = require('../respons/respons')
const posting    = require('../controllers/posting')
router.get('/posting/:file', posting.get)
router.post('/posting/upload/:id_user', posting.upload)
router.put('/posting/update/:id_user/:id', posting.update)
router.delete('/posting/delete/:id/:id_user', posting.delete)
module.exports = router